Try

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -23,7 +23,14 @@ jobs:
       - uses: actions/checkout@v2
 
       - name: Testing
-        run: solana
+        run: |
+          if [ ! -x $(command -v solana) ]; then
+            echo "solana not found 1"
+          fi
+
+          if ! [ -x $(command -v solana) ]; then
+            echo "solana not found 2"
+          fi
 
       - name: Set up Python 3.7
         uses: actions/setup-python@v1
